# Generated by Django 4.1.7 on 2023-09-08 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RentState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('max_size', models.IntegerField(editable=False)),
                ('status', models.CharField(choices=[('A', 'Approved'), ('P', 'Pending'), ('D', 'Draft'), ('R', 'Rejected')], default='active', max_length=10)),
                ('invitation_code', models.CharField(editable=False, max_length=6, unique=True)),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='owner_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rent State',
                'verbose_name_plural': 'Rent State',
                'db_table': 'rentstate',
            },
        ),
    ]
