# Generated by Django 4.1.7 on 2023-09-08 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rentiha', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RentIhaReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid_term', models.IntegerField(blank=True, null=True)),
                ('final', models.IntegerField(blank=True, null=True)),
                ('make_up', models.IntegerField(blank=True, null=True)),
                ('iha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentiha.rentiha')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rent Iha Report',
                'verbose_name_plural': 'Rent Iha Reports',
                'db_table': 'rent_iha_report',
                'unique_together': {('iha', 'member')},
            },
        ),
    ]
