# Generated by Django 4.1.7 on 2023-09-08 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iha', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentIha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_start_date', models.DateTimeField(blank=True, null=True)),
                ('rent_end_date', models.DateTimeField(blank=True, null=True)),
                ('is_renter', models.BooleanField(default=False)),
                ('iha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iha.i̇ha')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rent a Iha',
                'verbose_name_plural': 'Rent a Iha',
                'db_table': 'rentiha',
                'unique_together': {('member', 'iha')},
            },
        ),
    ]
